### ISSUE TITLE
What modifications are required to the DeepMind Lab release?

### ISSUE THREAD

**Issue by Jiankai-Sun** [agiantwhale/cognitive-mapping-agent#1]
Firstly, thank you for your excellent code!

```
model.py should be self contained. Other environment training files (such as environment.py or expert.py for expert data generation) are not expected to work without some modifications to the DeepMind Lab release.
```

What modifications are required to the DeepMind Lab release for environment training files (such as environment.py or expert.py for expert data generation)?

Could you please provide a detailed step-to-step instructions for us to follow?

Thank you!

**Comment by agiantwhale** [comment]
Hi,

Thanks for the interest in the work. Unfortunately I cannot provide the modified environment as it is part of work of [Vikas Dhiman's work](https://arxiv.org/abs/1802.02274).

Ultimately, I found adapting the paper to a continuous environment to be very difficult and didn't succeed. I've posted a short write up over [here](https://medium.com/@iljae/cognitive-mapping-and-planning-in-deepmind-lab-7f1c2d37fede), which may help you in fixing the problem.
